City-of-Helsinki/parking-permits-admin-ui

.editorconfig
package.json
src/App.tsx
src/components/Header.tsx
src/components/MainLayout.tsx
src/components/styles.module.scss
src/i18n/en.json
src/i18n/fi.json
src/i18n/index.ts
src/i18n/sv.json
src/index.scss
src/index.tsx
src/pages/Messages.tsx
src/pages/NotFound.tsx
src/pages/Permits.tsx
src/pages/Reports.tsx
src/pages/Returns.tsx
src/routes.tsx
yarn.lock

This PR setup the app with a basic layout with required packages.
Refs: PV-223
https://user-images.githubusercontent.com/1997039/134128823-c3b39e2b-1d33-405e-8ac0-60962f26ab1a.mov

A starting layout for the admin ui app

---

.editorconfig
Dockerfile
docker-compose.yml
nginx/nginx.conf

Added docker and docker-compose setup. Mostly copied from the parking-permits-ui

Docker setup

---

.husky/pre-commit
package.json
src/App.test.tsx
yarn.lock

Add husky git pre-commit hooks

---

src/services/mock.ts
src/types.ts

Add more fields to mock vehicle data

---

src/pages/EndPermit.module.scss
src/pages/EndPermit.tsx
src/pages/PermitDetail.module.scss

Minor ui fix

---

src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/EndPermit.tsx
src/pages/PermitDetail.tsx
src/pages/Permits.tsx

Handle graphql errors and show the error message in a toast notification
Related backend changes: https://github.com/City-of-Helsinki/parking-permits/pull/97

Handle errors with a toast error message

---

src/components/common/ChangeLogs.tsx
src/components/common/VehicleCategorySelect.tsx
src/components/common/ZoneSelect.tsx
src/components/createResidentPermit/PersonalInfo.tsx
src/components/createResidentPermit/VehicleInfo.module.scss
src/components/createResidentPermit/VehicleInfo.tsx
src/components/permitDetail/CustomerInfo.tsx
src/components/permits/PermitsDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/CreateResidentPermit.tsx
src/pages/PermitDetail.tsx
src/services/mock.ts
src/types.ts

Allow admins to manually enter permit details
Refs: PV-289

Update create resident permit layout

---

src/components/createResidentPermit/PersonalInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Update the translations for security ban chekcbox also
Refs: PV-295

Disable names fields if security ban is checked

---

src/components/createResidentPermit/PersonalInfo.tsx
src/components/createResidentPermit/VehicleInfo.module.scss
src/components/createResidentPermit/VehicleInfo.tsx
src/pages/CreateResidentPermit.tsx

The error messages are from backend, thus need to be translated there
Refs: PV-287

Handle errors for searching customer/vehicle and creating permits

---

src/components/common/ZoneSelect.tsx

Exclude zone id field from queries

---

src/components/common/ProductPriceRow.module.scss
src/components/common/ProductPriceRow.tsx
src/components/common/ZoneSelect.tsx
src/components/permitDetail/VehicleInfo.module.scss
src/components/permitDetail/VehicleInfo.tsx
src/components/residentPermit/PermitInfo.tsx
src/components/residentPermit/VehicleInfo.module.scss
src/components/residentPermit/VehicleInfo.tsx
src/components/residentPermit/consts.ts
src/pages/CreateResidentPermit.module.scss
src/pages/CreateResidentPermit.tsx
src/pages/EditResidentPermit.tsx
src/pages/EndPermit.tsx
src/pages/PermitDetail.tsx
src/types.ts
src/utils.ts

This PR also refactors data interfaces used by the components. The data interfaces become messy as we have different needs between the data fetched from the backend and the data sent to the backend. We create different interfaces for the input data now to match the graphql schema
https://user-images.githubusercontent.com/1997039/146932134-0f0c6f00-c610-4bae-9270-6be3b962eff4.mov
Refs: PV-293

Show product list prices in PermitDetail, EditResidentPermit and CreateResidentPermit page

---

src/components/SuperAdminLayout.module.scss
src/components/SuperAdminLayout.tsx
src/components/superAdmin/SideNav.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/Products.tsx
src/routes.tsx

Create routes and page layout for super admin pages
Refs: PV-293

Create super admin layout and a dummy products page

---

src/components/SuperAdminLayout.module.scss
src/components/common/DataTable.module.scss
src/components/superAdmin/products/ProductsDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/Products.module.scss
src/pages/superAdmin/Products.tsx
src/types.ts

Related backend PR: https://github.com/City-of-Helsinki/parking-permits/pull/122
Refs: PV-293

Add product list page

---

package.json
src/components/Header.tsx
src/components/common/ZoneSelect.tsx
src/components/residentPermit/PermitInfo.tsx
src/components/residentPermit/PersonalInfo.tsx
src/components/residentPermit/VehicleInfo.tsx
src/components/superAdmin/SideNav.tsx
src/components/superAdmin/products/LowEmissionDiscountSelect.tsx
src/components/superAdmin/products/ProductForm.module.scss
src/components/superAdmin/products/ProductForm.tsx
src/components/superAdmin/products/ProductTypeSelect.tsx
src/components/superAdmin/products/ProductUnitSelect.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/EditProduct.tsx
src/routes.tsx
src/types.ts
yarn.lock

https://user-images.githubusercontent.com/1997039/148920512-79683604-c899-4efe-8c19-78a88a947854.mov
Refs: PV-293

Implement edit product page

---

src/components/superAdmin/products/ProductForm.module.scss
src/components/superAdmin/products/ProductForm.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Make product form zone select wider

---

src/components/refunds/RefundsDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/RefundDetail.module.scss
src/pages/RefundDetail.tsx
src/pages/Refunds.tsx
src/routes.tsx
src/types.ts

Implement refund detail page

---

src/components/common/DataTable.module.scss
src/components/common/DataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Permits.tsx
src/pages/Refunds.tsx
src/pages/superAdmin/Products.tsx
src/types.ts

Show total results in datatable

---

src/components/permitDetail/PermitInfo.tsx
src/i18n/fi.json
src/pages/EditResidentPermit.module.scss
src/pages/EndPermit.module.scss
src/pages/EndPermit.tsx

The columns are in end permit page are stacked together. This PR fixed the layout.
no refs

Fix end permit layout

---

src/components/permits/PermitsDataTable.tsx
src/utils.ts

The last name should be put first
Refs: PV-376

Update customer name display format

---

package.json
src/components/permitDetail/PermitPriceChangeInfo.tsx
src/components/permitDetail/RefundInfoFixedPeriod.tsx
src/components/residentPermit/EditResidentPermitPreview.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/EndPermit.tsx
src/pages/RefundDetail.tsx
yarn.lock

Validate IBAN input

---

src/components/permitDetail/PermitInfo.tsx
src/components/permitDetail/PermitPriceChangeInfo.tsx
src/components/permitDetail/RefundInfoFixedPeriod.tsx
src/components/residentPermit/EditResidentPermitPreview.tsx
src/components/residentPermit/PermitInfo.tsx
src/components/residentPermit/consts.ts
src/pages/EditResidentPermit.tsx
src/pages/EndPermit.tsx
src/pages/PermitDetail.tsx
src/pages/RefundDetail.tsx
src/types.ts
src/utils.ts

Allow creating/updating permits with description

---

src/utils.ts

Seperate last name and first name with a comma

---

src/services/addressSearch.ts
src/types.ts
src/utils.ts

Remove sourceSystem and sourceId from addresses

---

src/components/residentPermit/PersonalInfo.tsx
src/services/addressSearch.ts
src/types.ts
src/utils.ts

Remove address source system

---

src/components/common/AddressSearch.tsx
src/components/residentPermit/EditResidentPermitForm.tsx
src/components/residentPermit/PermitInfo.tsx
src/components/residentPermit/PersonalInfo.tsx
src/components/residentPermit/VehicleInfo.tsx
src/pages/CreateResidentPermit.tsx
src/services/addressSearch.ts
src/types.ts
src/utils.ts

This PR fixed the bug that the addresses are not saved to the customer profile due to the interface change. This PR also refactors the interface for PersonalInfo, VehicleInfo, and PermitInfo components.
no refs

Fix address saving issue

---

src/pages/CreateResidentPermit.tsx
src/pages/EditResidentPermit.tsx
src/types.ts

Disable create button if customer already have two active permits

---

.env
.env.development.local.example
package.json
src/api/useApiToken.tsx
src/components/common/DataTable.module.scss
src/components/common/DataTable.tsx
src/components/orders/OrdersDataTable.tsx
src/components/permits/PermitsDataTable.tsx
src/components/refunds/RefundsDataTable.tsx
src/components/superAdmin/products/ProductsDataTable.tsx
src/export/useExportData.tsx
src/export/utils.ts
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Orders.tsx
src/pages/Permits.tsx
src/pages/Refunds.tsx
src/pages/superAdmin/Products.tsx
yarn.lock

Allow exporting data as csv files for permits, orders, refunds and products

---

src/components/orders/OrdersDataTable.tsx
src/components/permits/PermitsDataTable.tsx
src/components/permits/filterItems.ts
src/pages/CreateResidentPermit.tsx
src/pages/EditResidentPermit.tsx
src/pages/EndPermit.tsx
src/pages/Orders.tsx
src/pages/PermitDetail.tsx
src/pages/Permits.tsx
src/types.ts
yarn.lock

Note that the GraphQL ID type is resolved serialized as string even though they are saved as integers in backend
Refs: PV-375

Update interface to match data model fields update

---

src/components/orders/OrdersDataTable.tsx
src/pages/EndPermit.tsx
src/pages/Orders.tsx
src/pages/RefundDetail.tsx
src/pages/Refunds.tsx
src/routes.tsx
src/types.ts

Fix order/refund data interfaces after refactoring models

---

src/components/superAdmin/SideNav.tsx
src/components/superAdmin/lowEmissionCriteria/LowEmissionCriteriaDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/lowEmissionCriteria/LowEmissionCriteria.module.scss
src/pages/superAdmin/lowEmissionCriteria/LowEmissionCriteria.tsx
src/routes.tsx
src/types.ts

Low emission criteria super admin list view

---

src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.module.scss
src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/lowEmissionCriteria/CreateLowEmissionCriterion.module.scss
src/pages/superAdmin/lowEmissionCriteria/CreateLowEmissionCriterion.tsx
src/pages/superAdmin/lowEmissionCriteria/EditLowEmissionCriterion.module.scss
src/pages/superAdmin/lowEmissionCriteria/EditLowEmissionCriterion.tsx
src/routes.tsx

Add edit/create low emission criterion pages

---

src/components/orders/OrdersDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Orders.module.scss
src/pages/Orders.tsx

Create links to permit details in orders page

---

src/components/permitDetail/RefundInfoFixedPeriod.tsx
src/pages/EndPermit.tsx
src/types.ts

Remove the obsolete monthly price

---

src/components/permits/PermitsSearch.module.scss
src/components/permits/PermitsSearch.tsx
src/components/permits/PermitsSearchFilters.tsx
src/components/permits/utils.ts
src/components/types.ts
src/types.ts

Replace toggle button with checkboxes
Refs: PV-400

Improve permit search filters

---

src/components/common/LocationPicker.module.scss
src/components/common/LocationPicker.tsx
src/components/superAdmin/addresses/AddressForm.module.scss
src/components/superAdmin/addresses/AddressForm.tsx

Refactor address form

---

src/components/superAdmin/lowEmissionCriteria/LowEmissionCriteriaDataTable.tsx
src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.module.scss
src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/lowEmissionCriteria/LowEmissionCriteria.module.scss
src/pages/superAdmin/lowEmissionCriteria/LowEmissionCriteria.tsx

Various layout improvements for low emission criteria management
Refs: PV-415

Refactor low emission form

---

src/components/common/EuroClassSelect.tsx
src/pages/CreateResidentPermit.tsx
src/utils.ts

Fix permit pricing not updated on creating resident permit

---

src/components/refunds/RefundStatusLabel.module.scss
src/components/refunds/RefundStatusLabel.tsx
src/components/refunds/RefundStatusSelect.tsx
src/components/refunds/RefundsSearch.module.scss
src/components/refunds/RefundsSearch.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Refunds.tsx
src/styles/variables.scss
src/types.ts

Related backend PR: https://github.com/City-of-Helsinki/parking-permits/pull/229
Refs: PV-424

Add refunds search to refunds page

---

src/components/common/DataTable.module.scss
src/components/common/DataTable.tsx
src/components/common/table/Table.tsx
src/components/common/table/TableRow.module.scss
src/components/common/table/TableRow.tsx
src/components/refunds/RefundsDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Refunds.tsx

https://user-images.githubusercontent.com/1997039/172342353-3fedb32e-c5ba-4af2-a8a2-063f5f0e641b.mov
Refs: PV-425

Enable datatable checkbox selection

---

src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/RefundDetail.module.scss
src/pages/RefundDetail.tsx

Add "Download refund details as PDF"-functionality:

Add "Download refund details as PDF"-functionality

---

src/components/refunds/RefundsDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Refunds.tsx
src/types.ts

Show more fields to refunds datatable

---

src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/addresses/EditAddress.tsx
src/pages/superAdmin/lowEmissionCriteria/EditLowEmissionCriterion.tsx
src/pages/superAdmin/products/EditProduct.tsx

For product, low emission criteria and address.
Add translations for fi/sv/en.

Add Delete confirmation dialogs for SuperAdmin forms

---

src/components/MainLayout.module.scss
src/components/MainLayout.tsx
src/components/SuperAdminLayout.module.scss
src/components/common/CheckboxGroup.module.scss
src/components/common/CheckboxGroup.tsx
src/components/common/ZoneSelect.tsx
src/components/superAdmin/SideNav.tsx
src/components/superAdmin/announcements/AnnouncementForm.module.scss
src/components/superAdmin/announcements/AnnouncementForm.tsx
src/hooks/searchParam.ts
src/hooks/useSet.ts
src/i18n/fi.json
src/index.scss
src/pages/superAdmin/announcements/Announcements.module.scss
src/pages/superAdmin/announcements/Announcements.tsx
src/pages/superAdmin/announcements/CreateAnnouncement.tsx
src/pages/superAdmin/announcements/ViewAnnouncement.module.scss
src/pages/superAdmin/announcements/ViewAnnouncement.tsx
src/routes.tsx
src/types.ts
src/utils.ts

This PR adds new views to the superadmin side of the UI for listing, viewing and creating announcements.
The superadmin needs to be able to send announcements to the customers through the admin UI. This feature allows the superadmin to do just that.
[PV-346](https://helsinkisolutionoffice.atlassian.net/browse/PV-346)
[Related back-end PR](https://github.com/City-of-Helsinki/parking-permits/pull/279)
Manual poking, in conjuction with the back-end implementation. No unit tests.
- Confirm that you can find the announcements under the admin page's side navigation bar
- Clicking the announcements section should take you to the announcement list view
- Should show a list of announcements
- If there aren't any announcements, should show an empty list
- Clicking an announcement on the list should …

PV-346: Add announcements superadmin panel

---

src/components/Header.tsx
src/components/superAdmin/SideNav.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Messages.tsx
src/pages/Reports.tsx
src/pages/superAdmin/addresses/Addresses.module.scss
src/pages/superAdmin/addresses/Addresses.tsx
src/pages/superAdmin/lowEmissionCriteria/LowEmissionCriteria.tsx
src/pages/superAdmin/products/Products.module.scss
src/pages/superAdmin/products/Products.tsx
src/routes.tsx

Update Admin UI layouts:
- Remove Messages and Reports sections
- Remove Users-section from Super Admin
- Unify Super Admin section main layouts
- Update fi/sv/en-translations
Manually, by running local development build.
Check layout locally.

Update Admin UI layouts

---

src/components/common/StatusLabel.module.scss
src/components/common/StatusLabel.tsx
src/components/common/StatusTag.module.scss
src/components/common/StatusTag.tsx
src/components/permits/StatusSelect.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/styles/variables.scss
src/types.ts

Remove non-needed draft-status from search criteria.

Remove draft-status from search criteria

---

src/components/superAdmin/addresses/AddressesSearch.module.scss
src/components/superAdmin/addresses/AddressesSearch.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/superAdmin/addresses/Addresses.module.scss
src/pages/superAdmin/addresses/Addresses.tsx
src/types.ts

Adds search parameters in the superadmin address list view.
Addresses need to filtered by parameters.
[PV-459](https://helsinkisolutionoffice.atlassian.net/browse/PV-459)
Manually.
Test it out with the back-end changes.
The new address list view.

PV-459: Add address search parameters

---

src/components/superAdmin/addresses/AddressForm.tsx

Add requested swedish city field to Address-form.
Refs: [PV-480](https://helsinkisolutionoffice.atlassian.net/browse/PV-480)
Locally.

Add swedish city field to Address-form

---

src/components/common/PowerTypeSelect.tsx
src/components/residentPermit/VehicleInfo.tsx
src/components/residentPermit/consts.ts
src/components/superAdmin/lowEmissionCriteria/LowEmissionCriteriaDataTable.tsx
src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.tsx
src/pages/superAdmin/lowEmissionCriteria/EditLowEmissionCriterion.tsx
src/pages/superAdmin/lowEmissionCriteria/LowEmissionCriteria.tsx
src/types.ts

As of now power type has been a text choices with some hardcoded values which resulted in failure for some vehicles whose
power type were not know during the time of coding. So now its moved to be a model so that admin user can easily add the new power types as per the need in future.
[PV-483](https://helsinkisolutionoffice.atlassian.net/browse/PV-483)
Log in to admin panel and you can see Vehicle power type table

Vehicle power type

---

src/pages/Permits.tsx

Minimum role to create a permit is customer service
[PV-481](https://helsinkisolutionoffice.atlassian.net/browse/PV-481)

Minimum role to create a permit is customer service

---

.eslintrc
src/api/useUserRole.tsx
src/components/Header.tsx
src/components/MainLayout.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

User with ad account but not belonging to any ad groups should show unauthorised message.
[PV-280](https://helsinkisolutionoffice.atlassian.net/browse/PV-280)
Login to admin view with a user that do not have ad groups.

Non ad group user

---

src/pages/PermitDetail.tsx

Prevent closed permit editing in Admin UI to reduce editing complexities.
[PV-507](https://helsinkisolutionoffice.atlassian.net/browse/PV-507)
Locally.

Prevent closed permit editing in Admin UI

---

src/components/orders/OrdersDataTable.tsx
src/components/permitDetail/RefundInfoFixedPeriod.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/EndPermit.tsx
src/pages/Orders.tsx
src/pages/Permits.tsx
src/types.ts

Finetune Orders- and Permits-views.
Fixes: [PV-468](https://helsinkisolutionoffice.atlassian.net/browse/PV-468)
Locally.
Test locally.

Finetune Orders- and Permits-views

---

src/pages/Permits.tsx

Disable permit row-clicks and CSV-export from inspectors
Fixes: [PV-501](https://helsinkisolutionoffice.atlassian.net/browse/PV-501)

Disable permit row-clicks and CSV-export from inspectors

---

src/components/residentPermit/PermitInfo.tsx

Use contract type from the permit-object itself.
Refs: [PV-512](https://helsinkisolutionoffice.atlassian.net/browse/PV-512)

Use contract type from the permit-object itself

---

src/components/residentPermit/PermitInfo.tsx
src/components/residentPermit/consts.ts
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Update permit form end date handling.

Update permit form end date handling

---

src/components/common/ChangeLogs.tsx
src/components/orders/OrdersDataTable.tsx
src/components/permitDetail/CustomerInfo.tsx
src/components/refunds/RefundsDataTable.tsx
src/pages/CreateResidentPermit.tsx
src/utils.ts

Update all prices to have two decimals in Admin UI.
Also remove unused email-button.
[PV-503](https://helsinkisolutionoffice.atlassian.net/browse/PV-503)

Update all prices to have two decimals

---

src/components/residentPermit/PersonalInfo.tsx

Remove unnecessary address type text

Remove unnecessary address type text

---

src/components/common/AddressSearch.tsx

Add location to the address search query

---

src/components/common/AddressSearch.tsx

Fix address search with loading

---

src/components/MainLayout.module.scss
src/components/MainLayout.tsx
src/components/SuperAdminLayout.module.scss
src/components/SuperAdminLayout.tsx
src/components/footer/Footer.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Add footer-panel to Admin UI.
[PV-604](https://helsinkisolutionoffice.atlassian.net/browse/PV-604)
[PV-531](https://helsinkisolutionoffice.atlassian.net/browse/PV-531)
Manually through all views.
Check that the footer exists in all views.
[PV-604]: https://helsinkisolutionoffice.atlassian.net/browse/PV-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PV-531]: https://helsinkisolutionoffice.atlassian.net/browse/PV-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add footer-panel to Admin UI

---

src/i18n/sv.json

Fix swedish translation typo.
[PV-633](https://helsinkisolutionoffice.atlassian.net/browse/PV-633)
[PV-633]: https://helsinkisolutionoffice.atlassian.net/browse/PV-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix swedish translation typo

---

src/components/orders/OrdersDataTable.tsx

[PV-657](https://helsinkisolutionoffice.atlassian.net/browse/PV-657)
Tested manually in order search
[PV-657]: https://helsinkisolutionoffice.atlassian.net/browse/PV-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set default to empty string if no order permits

---

src/components/permitDetail/VehicleInfo.tsx
src/components/residentPermit/VehicleInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

[PV-740](https://helsinkisolutionoffice.atlassian.net/browse/PV-740)
[PV-740]: https://helsinkisolutionoffice.atlassian.net/browse/PV-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated translations for Traficom messages

---

src/components/residentPermit/VehicleInfo.tsx

[PV-740](https://helsinkisolutionoffice.atlassian.net/browse/PV-740)
In admin UI, try to trigger Traficom error message (e.g. decomissioned vehicle)
[PV-740]: https://helsinkisolutionoffice.atlassian.net/browse/PV-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add pre-wrap style to notification to handle line breaks

---

src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

[PV-743](https://helsinkisolutionoffice.atlassian.net/browse/PV-743)
See also https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/PV/boards/183?selectedIssue=PV-753
[PV-743]: https://helsinkisolutionoffice.atlassian.net/browse/PV-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Translations updates

---

src/components/permitDetail/PermitInfo.tsx
src/components/residentPermit/PermitInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/pages/EditResidentPermit.tsx
src/pages/PermitDetail.tsx
src/types.ts
src/utils.ts

[PV-690](https://helsinkisolutionoffice.atlassian.net/browse/PV-690)
[PV-690]: https://helsinkisolutionoffice.atlassian.net/browse/PV-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bypass Traficom setting added to admin UI

---

src/components/common/StatusLabel.module.scss
src/components/common/StatusLabel.tsx
src/components/common/StatusTag.module.scss
src/components/common/StatusTag.tsx
src/components/permits/StatusSelect.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/styles/variables.scss
src/types.ts

Add permit cancelled status.
[PV-784](https://helsinkisolutionoffice.atlassian.net/browse/PV-784)
Manually in Admin UI.
[PV-784]: https://helsinkisolutionoffice.atlassian.net/browse/PV-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add permit cancelled status

---

src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/PermitDetail.tsx

Refs: PV-798
[PV-798](https://helsinkisolutionoffice.atlassian.net/browse/PV-798)
[PV-798]: https://helsinkisolutionoffice.atlassian.net/browse/PV-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new Change history types to GraphQL and translations.

---

src/pages/EditResidentPermit.tsx

`canExtendPermit` -> `canAdminExtendPermit` in admin UI.

Use canAdminExtendPermit property

---

src/components/permitDetail/VehicleInfo.module.scss
src/components/permitDetail/VehicleInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Refs: PV-666
[PV-666](https://helsinkisolutionoffice.atlassian.net/browse/PV-666
)
[PV-666]: https://helsinkisolutionoffice.atlassian.net/browse/PV-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show temporary vehicle times in permit detail page.

---

src/components/residentPermit/PersonalInfo.tsx

address
Refs: PV-787
[PV-787](https://helsinkisolutionoffice.atlassian.net/browse/PV-787)
Switch between primary and temporary addresses.
The address apartment should also be updated for the permit address to use the correct value.
[PV-787]: https://helsinkisolutionoffice.atlassian.net/browse/PV-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set correct address apartment when switching from primary to/from temp

---

src/components/permitDetail/TemporaryVehicle.tsx

[PV-665](https://helsinkisolutionoffice.atlassian.net/browse/PV-665)
See https://github.com/City-of-Helsinki/parking-permits/pull/499
[PV-665]: https://helsinkisolutionoffice.atlassian.net/browse/PV-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set start date to current date

---

src/auth/index.ts
src/components/permits/PermitsDataTable.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/Permits.tsx
src/types.ts

[PV-813](https://helsinkisolutionoffice.atlassian.net/browse/PV-813)
[PV-813]: https://helsinkisolutionoffice.atlassian.net/browse/PV-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Admin UI search fixes

---

src/i18n/en.json
src/utils.ts

Allow permit editing for all cases except when the permit is closed.
[PV-849](https://helsinkisolutionoffice.atlassian.net/browse/PV-849)
[PV-849]: https://helsinkisolutionoffice.atlassian.net/browse/PV-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow permit editing for all cases except when the permit is closed

---

src/components/footer/Footer.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Add accessibility report to footer 
[PV-842](https://helsinkisolutionoffice.atlassian.net/browse/PV-842)
Accessibility report should be visible in the footer.
[PV-842]: https://helsinkisolutionoffice.atlassian.net/browse/PV-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add accessibility report to footer

---

src/components/residentPermit/EditResidentPermitForm.tsx
src/components/residentPermit/PersonalInfo.tsx

No longer remove customer email or phone when re-fetching customer data from dvv.
[PV-850](https://helsinkisolutionoffice.atlassian.net/browse/PV-850)
Customer email or phone number should stay intact in their respective fields when customer data is searched from dvv with national id.
[PV-850]: https://helsinkisolutionoffice.atlassian.net/browse/PV-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

No longer remove customer email or phone when re-fetching customer data from dvv.

---

src/components/permitDetail/VehicleInfo.tsx
src/components/residentPermit/EditResidentPermitForm.tsx
src/components/residentPermit/PermitInfo.module.scss
src/components/residentPermit/PermitInfo.tsx
src/components/residentPermit/VehicleInfo.module.scss
src/components/residentPermit/VehicleInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/CreateResidentPermit.tsx

Updates:
- Add permit legend with permit pricing explanations
- Move permit prices under permit info
- Update fi/sv/en-translations
[PV-867](https://helsinkisolutionoffice.atlassian.net/browse/PV-867)
Manually.
[PV-867]: https://helsinkisolutionoffice.atlassian.net/browse/PV-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update permit prices layout

---

src/api/ApiAccessTokenProvider.tsx
src/auth/HandleCallback.tsx
src/index.tsx

Fix bug where api tokens are not available on first page load

Fix bug where api tokens are not available on first page load

---

package.json
yarn.lock

Update hds-react to 3.11.0

---

src/components/permitDetail/EndPermitDialog.tsx

Switch order of radio buttons
[PV-893](https://helsinkisolutionoffice.atlassian.net/browse/PV-893)
Order of selections should be switched.
[PV-893]: https://helsinkisolutionoffice.atlassian.net/browse/PV-893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switch order of radio buttons

---

src/components/permitDetail/TemporaryVehicle.tsx

Fix wrong timestamp
[PV-732](https://helsinkisolutionoffice.atlassian.net/browse/PV-732)
When adding temporary vehicle in admin ui, start time should be the current time instead of +1 hr.
[PV-732]: https://helsinkisolutionoffice.atlassian.net/browse/PV-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix wrong timestamp

---

src/i18n/sv.json

Add missing swedish translations
[PV-881](https://helsinkisolutionoffice.atlassian.net/browse/PV-881)
[PV-881]: https://helsinkisolutionoffice.atlassian.net/browse/PV-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing swedish translations

---

src/pages/CreateResidentPermit.tsx

Use permit id from response.
[PV-909](https://helsinkisolutionoffice.atlassian.net/browse/PV-909)
Manually.
[PV-909]: https://helsinkisolutionoffice.atlassian.net/browse/PV-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use permit id from response

---

src/pages/superAdmin/announcements/Announcements.tsx

Add localization to time so it is displayed in local time and with correct localization.
Fixes a bug where shown time is UTC time instead of local time.
Time shown in Ylläpito > Ilmoitukset should now be local time.

Add localization to displayed time

---

src/components/orders/OrdersDataTable.tsx
src/utils.ts

Fix date formatting which sometimes caused incorrect year to appear.
Order payment date in admin ui sometimes had a wrong year.
All dates should now be correct in the order table.
Example in prod: 134522

Fix date formatting

---

CHANGELOG.md
package.json

Release 1.5.2

---

src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Change button text when creating new resident permit
Buttons should show new text in all languages.

Change button text when creating new resident permit

---

CHANGELOG.md
package.json

Release 1.5.3

---

src/components/permitDetail/TemporaryVehicle.tsx

Disable button until request complete. Prevents dublicate actions.

Disable button until request complete

---

src/components/permitDetail/VehicleInfo.module.scss
src/components/permitDetail/VehicleInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json

Update temporary vehicle title text.
Refs: SHPPWS-21

SHPPWS-21: Update temporary vehicle title text

---

src/components/permitDetail/PermitPriceChangeInfo.tsx
src/components/permitDetail/RefundInfo.tsx
src/i18n/en.json
src/i18n/fi.json
src/i18n/sv.json
src/pages/EndPermit.tsx

Features:
- Add success- and tooltip-texts to IBAN-fields
- Allow empty IBAN in EndPermit
- Change IBAN TextInput to be optional in RefundInfo
- Update fi/sv/en-messages
Refs: SHPPWS-36

SHPPWS-36: Improve IBAN-handling
