- src/components/common/ZoneSelect.tsx
- src/components/createResidentPermit/VehicleInfo.tsx
- src/components/permitDetail/EndPermitDialog.module.scss
- src/components/permitDetail/EndPermitDialog.tsx
- src/components/permitDetail/PermitInfo.tsx
- src/components/permitDetail/RefundInfoFixedPeriod.module.scss
- src/components/permitDetail/RefundInfoFixedPeriod.tsx
- src/components/permitDetail/RefundInfoOpenEnded.module.scss
- src/components/permitDetail/RefundInfoOpenEnded.tsx
- src/components/permitDetail/VehicleInfo.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/CreateResidentPermit.tsx
- src/pages/EndPermit.module.scss
- src/pages/EndPermit.tsx
- src/pages/PermitDetail.module.scss
- src/pages/PermitDetail.tsx
- src/routes.tsx
- src/services/mock.ts
- src/types.ts
Admins can end permits from the permit detail page by clicking the end permit button if the permit can be ended.  If the permit cannot be ended, the button will be disabled.
Admins can choose from ending permit immediately or ending permit after the current period. For a fixed period permit, an IBAN is required for creating the refund. A permit that has been ended "after the current period" previously can still be ended immediately, but no need for IBAN input as the refund has already been created.
https://user-images.githubusercontent.com/1997039/142994111-2efe30f0-f149-4b77-a82e-65f78f0966da.mov
> Implement end permit UI

- src/components/createResidentPermit/PermitInfo.tsx
- src/utils.ts
Remove seconds and use international standard for time
This PR also fixes the end time calculation when creating resident permit.
Refs: PV-294
> Update time formatting

- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/EndPermit.tsx
This is leftover from previous refactoring of resdent permit layout (where we remove the vehicle owner/holder selection)
no refs
> Remove holder from vehicle node query

- src/components/Header.tsx
- src/components/permitDetail/RefundInfoFixedPeriod.tsx
- src/components/refunds/RefundsDataTable.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/CreateResidentPermit.tsx
- src/pages/EndPermit.tsx
- src/pages/Refunds.module.scss
- src/pages/Refunds.tsx
- src/pages/Returns.tsx
- src/routes.tsx
- src/services/addressSearch.ts
- src/types.ts
We have major refactoring on the refund calculation and related object interfaces. This PR updates the interfaces and also adds a refund list page.
Currently, refunds are only created when ending permits in Admin UI. The next step would be to create refunds for changing permits when the price of the permit goes down.
Related backend PR: 
https://github.com/City-of-Helsinki/parking-permits/pull/135
Refund list view:
Refs: PV-232
> Update refund interface and add refund list page

- src/components/permitDetail/PermitPriceChangeInfo.module.scss
- src/components/permitDetail/PermitPriceChangeInfo.tsx
- src/components/residentPermit/EditResidentPermitForm.module.scss
- src/components/residentPermit/EditResidentPermitForm.tsx
- src/components/residentPermit/EditResidentPermitPreview.module.scss
- src/components/residentPermit/EditResidentPermitPreview.tsx
- src/components/residentPermit/PermitInfo.tsx
- src/components/residentPermit/consts.ts
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/CreateResidentPermit.tsx
- src/pages/EditResidentPermit.module.scss
- src/pages/EditResidentPermit.tsx
- src/pages/EndPermit.module.scss
- src/routes.tsx
- src/types.ts
- src/utils.ts
This PR implements three different cases when the admin updating the resident permit:
1. if the price of the permit does not change, it displays the change preview and price info
2. if the price of the permit goes up, it displays the change preview and on extra payment needed. The admin can confirm new order after the customer's payment is confirmed
3. if the price of the permit goes down, it displays the change preview and refund amount. The admin can optionally enter a IBAN provided by the customer. After the admin confirms the refund, a refund will be created.
Refs: PV-337
https://user-images.githubusercontent.com/1997039/155979527-1982f6f8-5088-4210-b1be-65c9e80f05cb.mov
> Update resident permit refund: refund, extra payment and no price change cases

- src/components/residentPermit/PermitInfo.tsx
- src/i18n/fi.json
Set the fields to read only doesn't prevent changing the value through
widget buttons
Refs: PV-373
> Disable the number input and date input when editing permits

- src/components/common/AddressSearch.tsx
- src/components/permitDetail/CustomerInfo.tsx
- src/components/permits/PermitsDataTable.tsx
- src/components/residentPermit/EditResidentPermitForm.tsx
- src/components/residentPermit/PersonalInfo.module.scss
- src/components/residentPermit/PersonalInfo.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/CreateResidentPermit.tsx
- src/pages/EditResidentPermit.tsx
- src/pages/EndPermit.tsx
- src/pages/PermitDetail.tsx
- src/pages/Permits.tsx
- src/types.ts
- src/utils.ts
The UI for address selection is updated and there's no need to use an edit button. Admins could choose between two addresses, as well as enter address details. Also we include other address information in permit detail page and permit list view.
Note that we are using **primary address** and **other address** in the code to match the naming in both backend and frontend. But they are presented as **permanent** and **temporary** addresses.
Refs: PV-385
> Improve address UI

- src/components/common/AddressSearch.tsx
- src/components/residentPermit/PersonalInfo.tsx
- src/pages/CreateResidentPermit.tsx
- src/types.ts
Previously the zone field is not automatically selected when fetching a new customer profile from DVV, or switching to use another address.
Refs: PV-327, PV-385
> Auto-select the zone when fetch profile from backend or switch the address

- azure-pipelines-develop.yml
- azure-pipelines-release.yml
There was a PR to merge the change to the main branch directly, which will result in a two-way syncing (main -> develop and develop -> main). It is better to merge the changes to develop and then sync the develop branch to the main branch. 
no refs
> Add batch trigger to azure-pipelines-release.yml

- src/components/superAdmin/addresses/AddressForm.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/superAdmin/addresses/CreateAddress.tsx
- src/pages/superAdmin/addresses/EditAddress.tsx
The field reacts to location changes and queries the zone for the location when the user clicks a new location on the map.
Refs: PV-411
> Add a readonly zone field to AddressForm

- src/pages/CreateResidentPermit.tsx
- src/pages/EditResidentPermit.tsx
- src/pages/EndPermit.tsx
- src/pages/PermitDetail.tsx
- src/pages/superAdmin/addresses/EditAddress.tsx
- src/pages/superAdmin/products/EditProduct.tsx
The query caching causes problems that an updated object is not updated in the UI
no refs
> Apply no-cache fetch policy for queries

- src/components/refunds/RefundsDataTable.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/Refunds.module.scss
- src/pages/Refunds.tsx
Currently we do not have proper admin roles support, so both request for approval and accept refunds buttons are displayed to admins. The buttons are only enabled when selected refunds have the right statuses.
Refs: PV-423
> Allow admins to request refunds for approval and accept refunds

- src/pages/RefundDetail.tsx
Fix the error that causes the refund detail page to crash.
Navigating to a refund detail page (Returns > click a refund row) doesn't load because of an error. The error was caused by missing fields in the refund detail query.
Manually, against a local development API and the test API.
- Open the site, log in
- Navigate to "Returns"
- Click a row
- Nothing should explode and the refund details should show up (instead of a blank page)
- The console log should be free of any view-related errors
What the view should look like.
> PV-438: Fix refund detail page error

- src/components/superAdmin/addresses/AddressForm.tsx
`Save` button in address component is always being disabled.
Since address component  `save` button is always disabled it was preventing user to do any modification to the existing or add new address.
[PV-448](https://helsinkisolutionoffice.atlassian.net/browse/PV-448)
Login to admin ui. Check on tab `Ylläpito` select any address and try modifying it or try to create a new address.
Login to admin ui. Check on tab `Ylläpito` select any address and try modifying it or try to create a new address.
> Fix Address component save button always being disabled

- src/components/permits/PermitsDataTable.tsx
- src/components/permits/PermitsSearch.module.scss
- src/components/permits/PermitsSearch.tsx
- src/components/refunds/RefundsDataTable.tsx
- src/components/refunds/RefundsSearch.module.scss
- src/components/refunds/RefundsSearch.tsx
- src/i18n/fi.json
- src/pages/Orders.module.scss
- src/pages/Orders.tsx
- src/pages/Permits.module.scss
- src/pages/Permits.tsx
- src/pages/Refunds.module.scss
- src/pages/Refunds.tsx
Adds a search button, makes the query lazy (i.e. doesn't fire immediately but only after clicking the search button), and makes the pages look similar to the orders view. Applies to both the refunds and the permits view.
In a nutshell; the search functionality changes are required for GDPR reasons, related to logging.
The styling issue, not so much, but it probably looks nicer if each search view doesn't look different to each other. And it makes the code more similar to each other as well.
[PV-433](https://helsinkisolutionoffice.atlassian.net/browse/PV-433)
[PV-453](https://helsinkisolutionoffice.atlassian.net/browse/PV-453)
[PV-458](https://helsinkisolutionoffice.atlassian.net/browse/PV-458)
Manually. No unit tests.
In both views,:
- Check that when opening the page, there's nothing …
> PV-453/PV-433/PV-458: In refunds/permits, add search buttons, make the query lazy and unify the styles

- .eslintrc
- package.json
- src/api/useUserRole.tsx
- src/components/Header.tsx
- src/components/common/DataTable.tsx
- src/components/common/table/Table.tsx
- src/components/common/table/TableRow.tsx
- src/components/refunds/RefundsDataTable.tsx
- src/pages/RefundDetail.tsx
- src/pages/Refunds.tsx
- yarn.lock
Role base access control admin UI
UI differences between admin roles:
- All tabs and all functions visible
- Only show permits, orders and refunds tabs
- Refund-tab with both “Request for approval“- and “Accept refunds“-buttons
- Only show permits, orders and refunds tabs
- Refund-tab with only “Request for approval“ button
- (Optional: hide checkboxes from “Awaiting approval” status rows in returns, because they aren’t functional for this role)
- Only show permits, orders and refunds tabs
- In returns tab:
- Hide sticky bottom with buttons
- Hide checkboxes and “select all” function
- Only show permits, orders and refunds tabs
- In permits tab, hide all buttons except “download as pdf”
- In returns tab, once a single return is opened:
- Change the input fields of name and IBAN to …
> Role base access control admin UI

- .env
- src/components/residentPermit/EditResidentPermitForm.tsx
- src/components/superAdmin/SideNav.tsx
- src/components/superAdmin/customers/CustomerCard.module.scss
- src/components/superAdmin/customers/CustomerCard.tsx
- src/components/superAdmin/customers/CustomersSearch.module.scss
- src/components/superAdmin/customers/CustomersSearch.tsx
- src/export/useExportData.tsx
- src/export/utils.ts
- src/i18n/fi.json
- src/pages/CreateResidentPermit.tsx
- src/pages/superAdmin/customers/Customers.tsx
- src/pages/superAdmin/customers/ViewCustomer.module.scss
- src/pages/superAdmin/customers/ViewCustomer.tsx
- src/routes.tsx
- src/types.ts
- src/utils.ts
- Add the customers panel in superadmin.
- Add a button for downloading the customer data.
- Fix the annoying reload issue in superadmin (when clicking a link in the superadmin side navigation, it reloads the whole page -> no more!)
- Change other customer queries to use the new query object instead of searching by national ID number
The admin needs to be able to view and download customer data.
[PV-421](https://helsinkisolutionoffice.atlassian.net/browse/PV-421)
[PV-444](https://helsinkisolutionoffice.atlassian.net/browse/PV-444)
Manually, in tandem with the back-end changes.
- Confirm that you can find the customers under the admin page's side navigation bar
- Clicking the customers section should take you to the customers list view
- Should show an empty table at first
- After …
> PV-421/PV-444: Add customers panel in superadmin, add retrieve customer data button

- src/export/utils.ts
- src/pages/Orders.tsx
Orders CSV export was missing the query parameters.
The orders CSV export doesn't work without search parameters... and was also missing the search parameters. This fixes it.
[PV-463](https://helsinkisolutionoffice.atlassian.net/browse/PV-463)
Manually, against the back-end changes.
Export a CSV in the orders view. Use the fixed back-end; some parameters do not work without it (i.e. any parameter with a multi-part name, like `contractTypes`)
> PV-463: Fix orders CSV export

- src/api/useUserRole.tsx
- src/components/Header.tsx
- src/components/SuperAdminLayout.tsx
- src/components/permitDetail/CustomerInfo.tsx
- src/components/permits/PermitsDataTable.tsx
- src/pages/Orders.tsx
- src/pages/PermitDetail.tsx
- src/pages/Permits.tsx
- src/pages/Refunds.tsx
Role base access control admin UI for inspectors
- Only show permits tab
- Don’t show personal information in the table
- Ensure the downloadable .csv doesn’t include personal information
- Once a permit is opened:
- In the “Customer information” column in the middle, only show “Parking zone” information
- Hide “Change history” in the bottom
- Hide all the buttons in the bottom, also the .pdf download button
> Role base access control for inspectors

- src/components/residentPermit/PersonalInfo.tsx
- src/utils.ts
Admin UI: Enabling "Non-disclosure for personal safety"-checkbox (Turvakielto) should clear name and address fields always.
Clear name and address fields always when "Non-disclosure for personal safety"-checkbox is enabled.
[PV-464](https://helsinkisolutionoffice.atlassian.net/browse/PV-464)
Login as any admin account and try to buy new permit. Input the value of some fields such as name and address then check 
`Non-disclosure for personal safety` checkbox. It disable the fields but doesn't clear its value.
Login as any admin account and try to buy new permit. Input the value of some fields such as name and address then check 
`Non-disclosure for personal safety` checkbox. It should now clear the the fields and disable it as well.
> Clear name and address fields always when "Non-disclosure for personal safety"-checkbox is enabled

- src/pages/Permits.tsx
- src/types.ts
Inspectors uses limitedPermit query in order to search the permits. And therefore the process of extracting the data from the response should be updated depending on the query used.
[PV-478](https://helsinkisolutionoffice.atlassian.net/browse/PV-478)
Login as an inspectors and search the permits.
> Fix inspectors not being able to search the permits

- src/utils.ts
Initialize the `powerType` field in vehicle input correctly.
When editing a resident permit, if you don't change the vehicle power type, it sneaks a `__typename` field there. This causes errors.
Manually.
Edit a resident permit (after applying https://github.com/City-of-Helsinki/parking-permits/pull/307, editing a resident permit doesn't work at all before it)
> Fix: Fix powerType in convertToVehicleInput

- src/components/common/ChangeLogs.tsx
- src/i18n/fi.json
- src/pages/PermitDetail.tsx
- src/types.ts
Add new columns in parking permit history. Add support for the new parking permit event model. Not my best work, please pay attention to the code you're reviewing.
[PV-350](https://helsinkisolutionoffice.atlassian.net/browse/PV-350)
Some very little manual testing.
See if events created in the back-end end up in the permit detail page.
> PV-350: Update parking permit history

- src/components/common/ChangeLogs.tsx
- src/i18n/fi.json
- src/pages/PermitDetail.tsx
Add temporary vehicles events, fix event column
[PV-350](https://helsinkisolutionoffice.atlassian.net/browse/PV-350)
Manually.
> PV-350: Add temporary vehicles events, fix event column

- src/pages/PermitDetail.tsx
Prevent future starting open-ended permit editing
Fixes: [PV-513](https://helsinkisolutionoffice.atlassian.net/browse/PV-513)
Locally.
Have future starting open-ended permit and see if the permit "Edit"-button is disabled.
Future starting fixed-period permits and already started open-ended permits should still be editable.
> Prevent future starting open-ended permit editing

- src/components/common/ConfirmDialog.tsx
- src/components/superAdmin/addresses/AddressForm.module.scss
- src/components/superAdmin/addresses/AddressForm.tsx
- src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.module.scss
- src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.tsx
- src/components/superAdmin/products/ProductForm.module.scss
- src/components/superAdmin/products/ProductForm.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/superAdmin/addresses/CreateAddress.tsx
- src/pages/superAdmin/addresses/EditAddress.tsx
- src/pages/superAdmin/lowEmissionCriteria/CreateLowEmissionCriterion.tsx
- src/pages/superAdmin/lowEmissionCriteria/EditLowEmissionCriterion.tsx
- src/pages/superAdmin/products/CreateProduct.tsx
- src/pages/superAdmin/products/EditProduct.tsx
Update SuperAdmin form buttons. Add cancel-button to address-, product- and lowemissioncriteria-forms. Also use red-colored `danger`-variant buttons in delete-confirmation dialogs in those entity deletion cases.
Fixes: [PV-422](https://helsinkisolutionoffice.atlassian.net/browse/PV-422)
Locally.
> Update SuperAdmin form buttons

- src/components/permitDetail/PermitInfo.tsx
Show the current period end time for open-ended permits.
[PV-519](https://helsinkisolutionoffice.atlassian.net/browse/PV-519)
Manually.
Check that an ongoing open-ended permit has the correct end time (i.e. the end of the current 1-month period)
[PV-519]: https://helsinkisolutionoffice.atlassian.net/browse/PV-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PV-519: Show the current period end time for open-ended permits

- src/components/common/AddressSearch.tsx
- src/components/permitDetail/CustomerInfo.tsx
- src/components/permitDetail/PermitInfo.tsx
- src/components/permits/PermitsDataTable.tsx
- src/components/residentPermit/EditResidentPermitForm.tsx
- src/components/residentPermit/PersonalInfo.tsx
- src/components/superAdmin/addresses/AddressForm.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/CreateResidentPermit.tsx
- src/pages/EditResidentPermit.tsx
- src/pages/EndPermit.tsx
- src/pages/PermitDetail.tsx
- src/pages/Permits.tsx
- src/types.ts
- src/utils.ts
Add apartment support for addresses.
[PV-591](https://helsinkisolutionoffice.atlassian.net/browse/PV-591)
Manually by creating new permit with apartment details and editing existing permit apartment details.
Test cases:
1. Create new permit with apartment details
2. Edit existing permit apartment details
3. Search permits and observe that permit has apartment details in address
4. Search orders and observe that permit has apartment details in address
5. Open permit details form and observe that permit has apartment details in address (both customer primary or other address details and permit details)
6. Make CSV-export for permits
7. Make CSV-export for orders
8. Make PDF-export for permit
[PV-591]: https://helsinkisolutionoffice.atlassian.net/browse/PV-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> Add apartment support for addresses

- src/auth/oidc-react.ts
The polling runs every few minutes and fetches the latest user info from the OIDC server. If the token has expired (based on the `expired_at` value) the server will return a 401. A 403 may be returned if some other server setting has changed e.g. the user has had permissions removed.
In this case, we call `window.location.reload()` to force a browser reload. The application context will automatically show the login page if the token is missing or invalid, so the user will be shown this page and can log back in. Typically the token is set to expire in an hour, so this will force the user to log back in every hour. Currently the session will still expire, but the UI is just rendered unresponsive with no error messages until the user reloads the browser.
Note that this is not a perfect …
> Add browser reload to user info poll on session timeout

- src/pages/Permits.tsx
Change the default status to “All” in Permits search.
[PV-621](https://helsinkisolutionoffice.atlassian.net/browse/PV-621)
Manually using different permit search criteria.
Open Admin UI permits page and observe that the permit state dropdown is set to "All" by default. Search permits with different permit search criteria. 
[PV-621]: https://helsinkisolutionoffice.atlassian.net/browse/PV-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change default status to “All” in Permits search

- src/components/residentPermit/PersonalInfo.tsx
At the moment, it is not possible to search customer details from DVV in existing permit editing phase. Make it possible by always enable customer search button (but not the national id number text input field itself).
[PV-625](https://helsinkisolutionoffice.atlassian.net/browse/PV-625)
Locally by opening the permit edit form and changing customer name and address values to something else. Then ckicking the "Search"-button and it will restore the customer original values from DVV.
Test by editing the existing customer firstname, lastname andd address values. Click "Search"-button and observe that the original values are restored to the permit form.
[PV-625]: https://helsinkisolutionoffice.atlassian.net/browse/PV-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
> Always enable customer search button

- src/components/SuperAdminLayout.tsx
A race condition exists where default user role "0" is returned if the token is not yet available. In this case, the user is not considered a "super admin". Users without this role are redirected to the Permits page,  so even if the user is a super admin, they have already been redirected and the original destination is lost.
[PV-488](https://helsinkisolutionoffice.atlassian.net/browse/PV-488)
1. Log in as super admin EXT-asukptTkuusi@hel.fi
2. Navigate to http://localhost:3000/admin/products
3. Reload the browser 
4. You should remain on the Products page (i.e. Ylläpito)
5. Log out and log back in as EXT-asukptTviisi@hel.fi
6. Enter URL http://localhost:3000/admin/products
7. You should be redirected to Permits (Tunnukset) tab
[PV-488]: …
> Refreshing the page in admin pages takes the user back to permits

- src/pages/CreateResidentPermit.module.scss
- src/pages/CreateResidentPermit.tsx
Issue was caused by the z-index not being set on a fixed element. In addition some minor padding fixes were added so the buttons are not immediately adjacent to the edge of the footer block and the footer bar expands to the width of the page.
[PV-623](https://helsinkisolutionoffice.atlassian.net/browse/PV-623)
Tested manually (visual fix)
Navigate to Permits form, scroll up and down the page.
[PV-623]: https://helsinkisolutionoffice.atlassian.net/browse/PV-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>   Admin UI: Footer of the page interferes with the bottom selection

- src/utils.ts
This fix should ensure decimal values are rounded correctly e.g. 90.955 -> 90.96 and not 90.95.
[PV-622](https://helsinkisolutionoffice.atlassian.net/browse/PV-622)
Tested manually in console (the exact edge case is difficult to replicate in development)
[PV-622]: https://helsinkisolutionoffice.atlassian.net/browse/PV-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ensure better precision in formatting prices

- src/components/permitDetail/PermitPriceChangeInfo.tsx
- src/components/residentPermit/EditResidentPermitPreview.tsx
- src/types.ts
- src/utils.ts
Fix IBAN checking logic from permit edit preview for the following cases:
1. IBAN empty: show validation error and disable preview Save-button
2. IBAN given, but incorrect: show validation error and disable preview Save-button
3. IBAN given and correct: enable preview Save-button
4. IBAN not known option selected: enable preview Save-button
[PV-634](https://helsinkisolutionoffice.atlassian.net/browse/PV-634)
Manually.
[PV-634]: https://helsinkisolutionoffice.atlassian.net/browse/PV-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix IBAN checking logic from permit edit preview

- src/components/permitDetail/PermitPriceChangeInfo.tsx
1. Only new price is shown, not (crossed out) old price
2. Total sum for all months should not have "per month"
[PV-647](https://helsinkisolutionoffice.atlassian.net/browse/PV-647)
Edit an existing permit, making sure to change to different model of car with higher/lower pricing
[PV-647]: https://helsinkisolutionoffice.atlassian.net/browse/PV-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix new price and total for all months in summary

- src/components/residentPermit/EditResidentPermitForm.tsx
- src/components/residentPermit/PersonalInfo.tsx
- src/components/residentPermit/VehicleInfo.tsx
- src/pages/CreateResidentPermit.tsx
- src/pages/EditResidentPermit.tsx
When a new search is initiated for a person or vehicle, reset fields accordingly.
[PV-635](https://helsinkisolutionoffice.atlassian.net/browse/PV-635)
Create a new permit:
1. Enter an ID for the person search, click "Hae/Search".
2. Enter a registration number for vehicle search, click "Hae/Search"
3. Search for a new vehicle registration number. Existing vehicle details should be reset/set to default before new vehicle appears.
4. Search for a new person. All permit details should be reset/set to default before new person details appear.  You will then need to search for a vehicle belonging to that person.
Edit an existing permit:
1. Find an existing permit, open Edit form
2. Search for another vehicle, vehicle details should disappear before new vehicle appears. …
> Reset permit fields on person and vehicle search

- src/components/residentPermit/EditResidentPermitForm.tsx
- src/components/residentPermit/PersonalInfo.tsx
The primary address will also be selected only if the other address is not selected.
In addition, neither address should be selectable if there is no primary or other address available (e.g. with new permit or missing address info).
Refs: PV-638
[PV-638](https://helsinkisolutionoffice.atlassian.net/browse/PV-638)
Tested manually:
1. New permit, changing the user ID number
2. Editing an existing permit, selecting either address or looking up a new address
[PV-638]: https://helsinkisolutionoffice.atlassian.net/browse/PV-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ensure other address is only selected if available

- src/components/permitDetail/VehicleInfo.module.scss
- src/components/permitDetail/VehicleInfo.tsx
- src/components/residentPermit/VehicleInfo.module.scss
- src/components/residentPermit/VehicleInfo.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
Add Traficom copyrights for vehicle fields.
Update fi/sv/en-translations.
[PV-658](https://helsinkisolutionoffice.atlassian.net/browse/PV-658)
Manually.
[PV-658]: https://helsinkisolutionoffice.atlassian.net/browse/PV-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Traficom copyrights for vehicle fields

- src/components/residentPermit/EditResidentPermitPreview.tsx
[PV-721](https://helsinkisolutionoffice.atlassian.net/browse/PV-721)
Find an existing permit in admin UI. The "Save" button should always be enabled, and saving should always work.
[PV-721]: https://helsinkisolutionoffice.atlassian.net/browse/PV-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove IBAN and refund status rules for disabling "Save" button on edit

- src/components/residentPermit/PermitInfo.tsx
- src/pages/CreateResidentPermit.tsx
- src/types.ts
[PV-769](https://helsinkisolutionoffice.atlassian.net/browse/PV-769)
1. Create a permit. Min date should be today.
2. For same customer, create a second permit. Min date should be date of first permit.
Repeat 1 and 2 for start date in future.
[PV-769]: https://helsinkisolutionoffice.atlassian.net/browse/PV-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enforce start date for admin UI new permit start date

- src/components/residentPermit/PersonalInfo.tsx
[PV-787](https://helsinkisolutionoffice.atlassian.net/browse/PV-787)
Case 1: Existing customer, no temp address
1. Find a customer with no temporary address (or remove temp address from a customer in Django admin).
2. Look up customer+permit in admin UI.
3. In the "Hae osoite..." field, look up another address (can be any zone).
4. Once selected, click "Jatka". Permit address should match primary customer address.
5. Click "Tallenna". Permit should be updated with correct address.
Case 2: Existing customer, no primary address
Repeat steps 1-5, but with a customer with no primary address, but just a temp address. 
**Note:** the existing permit should have same address as the temp address, if you are editing in Django admin.
Regression testing:
Customer with both addresses: …
> Ensure that either primary or secondary address is selected.

- src/components/residentPermit/EditResidentPermitForm.tsx
[PV-803](https://helsinkisolutionoffice.atlassian.net/browse/PV-803)
1. Look up existing permit in admin UI e.g. 290200A905H.
2. Click "Hae" next to Hetu
3. Primary and/or other address should be updated automatically
4. Click "Jatka"
5. Permit address should be updated to match primary or other address
6. Click "Tallenna"
7. Permit should be saved correctly to database and all permit and customer address fields updated.
Regression testing:
* Change primary/other address using "Hae Osoite..." instead of updating from DVV.
* Change between primary and other address.
[PV-803]: https://helsinkisolutionoffice.atlassian.net/browse/PV-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Handle address fields from customer query-

- src/components/orders/OrdersDataTable.tsx
- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/pages/Orders.tsx
- src/types.ts
Add "Talpa order ID" column to orders.
[PV-830](https://helsinkisolutionoffice.atlassian.net/browse/PV-830)
Related backend PR: https://github.com/City-of-Helsinki/parking-permits/pull/514
New column should be visible and have talpa order id as values.
[PV-830]: https://helsinkisolutionoffice.atlassian.net/browse/PV-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Talpa order ID column to orders

- src/i18n/en.json
Change order date search text, since search functionality has changed.
[PV-831](https://helsinkisolutionoffice.atlassian.net/browse/PV-831)
When searching orders, date search should have new english translations.
[PV-831]: https://helsinkisolutionoffice.atlassian.net/browse/PV-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change order date search text

- src/components/permitDetail/TemporaryVehicle.tsx
Temporary vehicle permit minimum end date can now be same as the start date so one day permits can be issued.
Refs SHPPWS-7
[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)
> Change minimum date on Temporary permit end date

- src/components/refunds/RefundsDataTable.tsx
- src/pages/RefundDetail.tsx
- src/pages/Refunds.tsx
- src/types.ts
Update refunds to support multiple orders.
Related PR:s: https://github.com/City-of-Helsinki/parking-permits/pull/538
These have to be merged at the same time!
[PV-877](https://helsinkisolutionoffice.atlassian.net/browse/PV-877)
Manually.
Test that Refund-functions works normally.
[PV-877]: https://helsinkisolutionoffice.atlassian.net/browse/PV-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update refunds to support multiple orders

- public/silent_renew.html
- src/api/ApiAccessTokenProvider.tsx
- src/auth/HandleCallback.tsx
- src/auth/index.ts
- src/auth/useIsAuthReady.tsx
- src/auth/utils.tsx
- src/index.tsx
User tokens were frequently expired, but auto renewal was false and `silent_renew.html` was missing. This caused the renewal to get stuck and the loading spinner blocked the UI. It is unknown why the `oidc-client `used in `HDS Login,` still tried sent renewal events.
Fixed by adding the `silent_renewal.html` and changed auto renew to `true`.
Cleaned up some unnecessary code for api token retrieval and renewal checks.
Once the user and api tokens are fetched, the renewal is done under the hood and it is not necessary to indicate it to the user.
There is still one "loading" showing in the content area when api tokens are renewed. Could be removed. The user may fetch exactly at the same time api tokens are renewed, but then the query just fails and can be fetched again. The "loading" text …
> Fix issues with renewal 

- src/api/ApiClientProvider.tsx
- src/auth/LoginProvider.tsx
- src/hds/README.md
- src/hds/apolloClient/apolloClientModule.ts
- src/hds/apolloClient/authLink.ts
- src/hds/apolloClient/hooks.ts
- src/hds/apolloClient/index.ts
- src/hds/createApiTokenClientTracker.ts
The module is created and tested in HDS, but not released yet, so copied it.
The module adds automatically two ApolloLinks:
- one that appends auth headers
- one that awaits for api token renewal to end if it happens to be in progress at the same time
The created ApolloClient is passed to the ApolloClient context.
HDS has unit tests and tested locally by keeping admin ui open for 60+minutes and checking tokens are renewed and queries work.
> Added new Apollo client module to HDS Login

- src/api/useApiToken.tsx
- src/api/useUserRole.tsx
- src/api/waitForApiToken.ts
- src/export/useExportData.tsx
1) useUserRole depended on useApiToken to determine user role. Since useApiToken can return empty token during token renewal, this would cause spurious issues with user receiving a wrong role. Resolved by using user id token instead of api token to access user's AD groups.
2) useExportData relied on useApiToken to do a fetch request. Added an async helper function watForApiToken that waits up to 2 seconds for the apiToken to become available.
refs: HDS-2615
> fix: issues caused by api token renewal

- src/pages/superAdmin/addresses/Addresses.tsx
Address pagination did not work well when used together with the address search.
Change address form to use Apollo client lazy queries to remedy this behaviour.
[PV-843](https://helsinkisolutionoffice.atlassian.net/browse/PV-843)
Manually.
Test that address pagination works together with different searches.
[PV-843]: https://helsinkisolutionoffice.atlassian.net/browse/PV-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: use lazy query in address pagination

- src/components/orders/OrdersSearch.tsx
- src/components/permitDetail/TemporaryVehicle.tsx
- src/components/refunds/RefundsSearch.tsx
- src/components/superAdmin/lowEmissionCriteria/LowEmissionCriterionForm.tsx
- src/components/superAdmin/products/ProductForm.tsx
Add language-support for calendars in:
- OrdersSearch
- TemporaryVehicle
- RefundsSearch
- LowEmissionCriterionForm
- ProductForm
Refs: SHPPWS-85
> fix: add language-support for calendars

- src/pages/superAdmin/announcements/Announcements.tsx
- src/pages/superAdmin/announcements/ViewAnnouncement.tsx
- src/utils.ts
Refs SHPPWS-28 / Zendesk ticket 27942
This formats timestamps in Announcements list and when viewing the announcement.
After change when listing announcements:
After change when viewing announcement:
Manual testing in local development environment.
> SHPPWS-28: Fix announcement timestamp

- src/components/residentPermit/EditResidentPermitForm.module.scss
- src/components/residentPermit/EditResidentPermitPreview.module.scss
- src/pages/CreateResidentPermit.module.scss
- src/pages/EndPermit.module.scss
- src/pages/ExtendPermit.module.scss
- src/pages/PermitDetail.module.scss
- src/pages/Refunds.module.scss
Remove fixed positions from the form buttons.
This prevents button overlaps with the page footer-component.
> SHPPWS-54: Remove fixed positions from the form buttons

- src/i18n/en.json
- src/i18n/fi.json
- src/i18n/sv.json
- src/utils.ts
Updates:
- Update permit end dialog fi/sv/en-messages
- Update date format to match other date formats in the application
Open-ended permit validity period: 20.3.2025 11:36 - 19.5.2025 23:59
Time of permit ending testing 19.4.2025 11:04.
**1. Permit status before ending after current period:**
**2. Permit ending dialog:**
**3. Overview-page, where the refund is shown:**
**4. Permit status after ending after current period:**
**5. Permit change history updated:**
> SHPPWS-93: Update end permit dialog messages and date format

- src/components/permitDetail/TemporaryVehicle.tsx
Use permit end time as max dates.
Refs: SHPPWS-35
> SHPPWS-35: Use permit end time as max dates
